### ISSUE TITLE
Program generic animal system

### ISSUE THREAD

**Issue by jamalkoya** [saadjiqbal/brackeys-gj-2024#4]
Implement the core game systems required for MVP:
- [x] RNG for generating one of the following statuses: hunger, thirst, boredom and affection
- [x] A patience meter that slowly reduces if need is not being met
- [x] Display icon of status
- [ ] Increase patience meter after need has been met

**Comment by saadjiqbal** [comment]
Change status assignment from `5 -> 15` seconds to something much lower such as `2 -> 8` seconds.
